# logger options
image_save_iter: 10000       # How often do you want to save output images during training
image_display_iter: 5000       # How often do you want to display output images during training
display_size: 8              # How many images do you want to display each time
snapshot_save_iter: 20000     # How often do you want to save trained models
log_iter: 10                  # How often do you want to log the training stats

# optimization options
max_iter: 1000000             # maximum number of training iterations
batch_size: 8                 # batch size
weight_decay: 0.0001          # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.0001                    # initial learning rate
lr_policy: step               # learning rate scheduler
step_size: 100000             # how often to decay learning rate
gamma: 0.5                    # how much to decay learning rate
gan_w: 0                      # weight of adversarial loss
recon_w: 1                    # weight of image reconstruction loss
kl_w: 0
vgg_w: 1                      # weight of domain-invariant perceptual loss
train: True
net_version: v2

# data options
input_dim_a: 3                              # number of image channels [1/3]
input_dim_b: 3                              # number of image channels [1/3]
num_workers: 8                              # number of data loading threads
new_size: 128
sigma: 1                               # first resize the shortest image side to this size
crop_image_height: 128                      # random crop image of this height
crop_image_width: 128                       # random crop image of this width
root_dir: /home/sjqian/WFLW/Image     # dataset folder location
img_list: /home/sjqian/WFLW/train_98pt.txt
zoom_min: 0.5
zoom_max: 0.5
feature_weights: [
   1.0,
   1.0,
   1.0,
   1.0,
   1.0]
